version: '3.8'

services:
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION}
    container_name: prometheus-${NODE}
    volumes:
      - /volumes/prometheus/tsdb:/prometheus
      - /volumes/prometheus/config:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"
    depends_on:
      - alertmanager
    
  alertmanager:
    image: "prom/alertmanager:${AM_VERSION}"
    container_name: am-${NODE}
    restart: unless-stopped
    volumes:
      - "/volumes/alertmanager:/alertmanager/data"
      - "/volumes/alertmanager/config/alertmanager.yml:/etc/alertmanager/alertmanager.yml"
    ports:
      - "9093:9093"
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager/data'
    labels:
      org.label-schema.group: "monitoring"


  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    container_name: node_exporter-${NODE}
    hostname: node_exporter
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - "127.0.0.1:9100:9100"
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"
  
  blackbox:
      image: prom/blackbox-exporter
      container_name: blackbox-${NODE}
      hostname: blackbox
      ports:
        - "9115:9115"
      restart: unless-stopped
      command:
        - "--config.file=/etc/blackbox/blackbox.yml"
      volumes:
        - /volumes/blackbox:/etc/blackbox
      environment:
        TZ: "Europe/Moscow"
      labels:
        org.label-schema.group: "monitoring"

  grafana:
      image: grafana/grafana:10.0.12-ubuntu
      depends_on:
        - prometheus
      ports:
        - "3000:3000"
      volumes:
        - /volumes/grafana/conf/grafana.crt:/etc/grafana/grafana.crt
        - /volumes/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
        - /volumes/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards  
        - /volumes/grafana/conf/grafana.key:/etc/grafana/grafana.key
        - /volumes/grafana/conf/grafana.ini:/etc/grafana/grafana.ini
      restart: unless-stopped
      labels:
        org.label-schema.group: "monitoring"
