global:
  scrape_interval:     30s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 30s # Evaluate rules every 15 seconds. The default is every 1 minute.

# Remote write to long-term storage   
remote_write:
 - url: http://192.168.10.118:8428/api/v1/write
  remote_timeout: 15s
  queue_config:
    capacity: 100
    max_shards: 1000
    min_shards: 1
    max_samples_per_send: 1000
    batch_send_deadline: 5s
    min_backoff: 30ms
    max_backoff: 100ms

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - 192.168.1.117:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules.yaml"
  - "alert_rules_nodes.yml"
  - "alert_rules_http.yml"


scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  
  - job_name: 'node1'
    static_configs:
    - targets: ['node_exporter:9100']
  - job_name: 'docker1'
    static_configs:
    - targets: ['192.168.10.117:9323']
  - job_name: 'win-host'
    static_configs:
    - targets: ['192.168.10.129:9182']
  - job_name: 'snmp_interfaces'
    static_configs:
      - targets:
        - 192.168.10.118
    metrics_path: /snmp
    scrape_interval: 60s
    scrape_timeout: 30s
    params:
      module:
        - if_mib
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.10.117:9116

  - job_name: "ping"
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
        - 192.168.10.117
        - 192.168.10.129
        - 192.168.10.135
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__ 
        replacement: blackbox:9115   
    
  - job_name: "http check"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://skillfactory.ru
        - https://lms.skillfactory.ru
        - http://192.168.10.118:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__ 
        replacement: blackbox:9115
